language: python
cache: pip
python:
  # "2.6" not supported
  - "2.7"
  # "3.2" not supported
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install:
  - pip install -r test_requirements.txt -r requirements.txt
  - pip install coveralls
script:
  - nosetests -v --with-coverage -c tests/travis-tests.cfg